### ISSUE TITLE
Empty pop up when hitting Add block

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/blocks#47] opened 2020-11-13 17:00 UTC
Using Alpha 9 with clean browse cache, I still get this issue. Tried both Firefox Developer Edition and Safari.

**Comment by bastianallgeier** [comment] 2020-11-13 17:23
How does your blueprint file look like?

**Comment by HashandSalt** [comment] 2020-11-13 17:26
```
label:             Content Editorial
icon:              text

columns:

  # CONTENT
  left:
    width:         3/4
    sections:
      # BLOCKS
      content:
        type:      fields
        fields:
          longform:
            label: Content
            type: blocks



  # SETTINGS
  right:
    width:         1/4
    sections:

      # Files
      files:
        type:     files
        headline: Image Files
        layout:   list
        template: images

```

**Comment by bastianallgeier** [comment] 2020-11-13 17:29
Do you have any plugins running? Despite a weird display bug in Safari, the popup is working fine with your setup.

**Comment by bastianallgeier** [comment] 2020-11-13 17:29
Did you make sure to delete the media folder?

**Comment by HashandSalt** [comment] 2020-11-13 17:32
Clearing the media folder did not help. I do have the Editor field installed to. Heres my plugin (a couple are custom)

```
editor
entity-field
focus
forge-blocks
forge-methods
forge-tags
kirby-builder
kirby-minify-html
kirby3-hero
kirby3-schema
kirby3-seo
kirby3-webp
link-field
sitemapper
```

**Comment by Werbschaft** [comment] 2020-11-14 10:59
@HashandSalt as I know the Blocks field is not working when you have the editor or the original builder field from Tim installed. As soon as something doesn't work I always delete all plugins first to test for interactions

**Comment by HashandSalt** [comment] 2020-11-14 12:51
Removing the original builder and the editor didnt help in this case.

**Comment by Werbschaft** [comment] 2020-11-14 18:25
Really strange, if I use your blueprint all works fine here

<img width="1438" alt="Bildschirmfoto 2020-11-14 um 17 04 11" src="https://user-images.githubusercontent.com/2178466/99154323-28c40780-26af-11eb-9106-a1e848d1876f.png">

**Comment by bastianallgeier** [comment] 2020-11-24 11:26
I'm closing this here. I really cannot reproduce it.

**Closed by bastianallgeier** 2020-11-24 11:26 UTC
