### ISSUE TITLE
Stop drawer from closing accidentally 

### ISSUE THREAD

**Issue by rasteiner** [getkirby/blocks#53] opened 2020-11-16 08:52 UTC
Mouseup events outside of the drawer close it. This also happens, for example, when dragging to select text in a field and accidentally ending up outside of the drawer. 

The drawer could be closed on mousedown events instead.

**Comment by bastianallgeier** [comment] 2020-11-23 15:53
Hm, I cannot reproduce this. Which browser causes this for you?

**Comment by rasteiner** [comment] 2020-11-23 16:00
Have tested only Chrome 86 and 87 on Windows. Chromium Edge does it too (as one would expect).
Firefox on the other hand behaves :)

I'll try with the latest alpha

**Comment by rasteiner** [comment] 2020-11-23 16:13
Same in alpha 12. 

I guess it's kinda the same issue as here: https://github.com/getkirby/kirby/issues/2681

**Comment by bastianallgeier** [comment] 2020-11-23 16:44
Ahhh, now I found it and fixed it. Will be in the release tomorrow.

**Closed by bastianallgeier** 2020-11-23 16:44 UTC
Labels: type: bug 🐛
